export class currentMemberDetails {
    cifNum: string;
    custName: string;
    custName1: string;
    birthDate: string;
    oldIcNum: string;
    newIcNum: string;
    birthCertNum: string;
    passportNum: string;
    citizenCertNum: string;
    policeIdNum: string;
    armyIdNum: string;
    gender: string;
    citizenCountry: string;
    race: string;
    religion: string;
    regChannel: string;
    regLocation: string;
    regRcvdDate: string;
    epfRegDate: string;
    matrimAsset: string;
    handicapRemarks: string;
    cifStatus: string;
    residentStatus: string;
    homePhone: string;
    officePhone: string;
    mobilePhone: string;
    faxNum: string;
    emailAdd: string;
    webPage: string;
    electAddGrpSeq: string;
    prefComChannel: string;
    addresses: currentMemberAddress[];
    enforcementCode: string;
    employerAdd: string;
    employStartDate: string;
    liabilityCommenceMonth: string;
    businessConsCode: string;
    businessType: string;
    formASubMedia: string;
    numEmployees: string;
    blacklistIndicator: string;
    accStatus: string;
    primaryIdType: string;
    primaryIdNum: string;
    contactPersonName: string;
    contactDeptName: string;
    jobDesignCode: string;
    cifCategory: string;
    lastNominationDate: string;
    relatedLinkCode: string;
    deceasedDate: string;
    ageYears: string;
    ageMonths: string;
    maritalStatus: string;
    nomineeCheck: string;
    afisIndicator: string;
    leftThumbIndicator: string;
    rightThumbIndicator: string;
    thumbVerifiedDate: string;
    productType: string;
    dateCesLiability: string;
    accNum: string;
    formASubMode: string;
    freezeAccStatus: string;
    indicator1: string;
    indicator2: string;
    indicator3: string;
    indicator4: string;
    indicator5: string;
    indicator6: string;
    indicator7: string;
    indicator8: string;
    indicator9: string;
    indicator10: string;
    indicator11: string;
    indicator12: string;
    indicator13: string;
    indicator14: string;
    indicator15: string;
    indicator16: string;
    indicator17: string;
    indicator18: string;
    indicator19: string;
    indicator20: string;
    indicator21: string;
    indicator22: string;
    indicator23: string;
    indicator24: string;
    indicator25: string;
    indicator26: string;
    indicator27: string;
    indicator28: string;
    indicator29: string;
    indicator30: string;
    indicator31: string;
    indicator32: string;
    indicator33: string;
    indicator34: string;
    indicator35: string;
    indicator36: string;
    indicator37: string;
    indicator38: string;
    indicator39: string;
    indicator40: string;
    dateField1: string;
    dateField2: string;
    alpha10Field1: string;
    alpha10Field2: string;
    alpha20Field1: string;
    alpha20Field2: string;
    numericField1: string;
    numericField2: string;
    iAkaunLoginUserId: string;
    iAkaunStatus: string;
    pinReqDate: string;
    firstLoginDate: string;
    lastLoginDate: string;
    lastIAkaunStatusChgDate: string;
    cfiwiaCreationDate: string;
    cfiwiaLastMaintDate: string;
    closeStatusReasonCodeDesc: string;
    replaceMinutiae: string;
    tacMobilePhone: string;
    tacMobilePhoneStatus: string;
    activeContribTransferIndicator: string;

    constructor(memberDetails: any){
        this.cifNum = memberDetails.cifNum;
        this.custName = memberDetails.custName;
        this.custName1 = memberDetails.custName1;
        this.birthDate = memberDetails.birthDate;
        this.oldIcNum = memberDetails.oldIcNum;
        this.newIcNum = memberDetails.newIcNum;
        this.birthCertNum = memberDetails.birthCertNum;
        this.passportNum = memberDetails.passportNum;
        this.citizenCertNum = memberDetails.citizenCertNum;
        this.policeIdNum = memberDetails.policeIdNum;
        this.armyIdNum = memberDetails.armyIdNum;
        this.gender = memberDetails.gender;
        this.citizenCountry = memberDetails.citizenCountry;
        this.race = memberDetails.race;
        this.religion = memberDetails.religion;
        this.regChannel = memberDetails.regChannel;
        this.regLocation = memberDetails.regLocation;
        this.regRcvdDate = memberDetails.regRcvdDate;
        this.epfRegDate = memberDetails.epfRegDate;
        this.matrimAsset = memberDetails.matrimAsset;
        this.handicapRemarks = memberDetails.handicapRemarks;
        this.cifStatus = memberDetails.cifStatus;
        this.residentStatus = memberDetails.residentStatus;
        this.homePhone = memberDetails.homePhone;
        this.officePhone = memberDetails.officePhone;
        this.mobilePhone = memberDetails.mobilePhone;
        this.faxNum = memberDetails.faxNum;
        this.emailAdd = memberDetails.emailAdd;
        this.webPage = memberDetails.webPage;
        this.electAddGrpSeq = memberDetails.electAddGrpSeq;
        this.prefComChannel = memberDetails.prefComChannel;
        this.addresses = memberDetails.addresses.map((add: any) => new currentMemberAddress(add)),
        this.enforcementCode = memberDetails.enforcementCode;
        this.employerAdd = memberDetails.employerAdd;
        this.employStartDate = memberDetails.employStartDate;
        this.liabilityCommenceMonth = memberDetails.liabilityCommenceMonth;
        this.businessConsCode = memberDetails.businessConsCode;
        this.businessType = memberDetails.businessType;
        this.formASubMedia = memberDetails.formASubMedia;
        this.numEmployees = memberDetails.numEmployees;
        this.blacklistIndicator = memberDetails.blacklistIndicator;
        this.accStatus = memberDetails.accStatus;
        this.primaryIdType = memberDetails.primaryIdType;
        this.primaryIdNum = memberDetails.primaryIdNum;
        this.contactPersonName = memberDetails.contactPersonName;
        this.contactDeptName = memberDetails.contactDeptName;
        this.jobDesignCode = memberDetails.jobDesignCode;
        this.cifCategory = memberDetails.cifCategory;
        this.lastNominationDate = memberDetails.lastNominationDate;
        this.relatedLinkCode = memberDetails.relatedLinkCode;
        this.deceasedDate = memberDetails.deceasedDate;
        this.ageYears = memberDetails.ageYears;
        this.ageMonths = memberDetails.ageMonths;
        this.maritalStatus = memberDetails.maritalStatus;
        this.nomineeCheck = memberDetails.nomineeCheck;
        this.afisIndicator = memberDetails.afisIndicator;
        this.leftThumbIndicator = memberDetails.leftThumbIndicator;
        this.rightThumbIndicator = memberDetails.varightThumbIndicatorlue;
        this.thumbVerifiedDate = memberDetails.thumbVerifiedDate;
        this.productType = memberDetails.productType;
        this.dateCesLiability = memberDetails.dateCesLiability;
        this.accNum = memberDetails.accNum;
        this.formASubMode = memberDetails.formASubMode;
        this.freezeAccStatus = memberDetails.freezeAccStatus;
        this.indicator1 = memberDetails.indicator1;
        this.indicator2 = memberDetails.indicator2;
        this.indicator3 = memberDetails.indicator3;
        this.indicator4 = memberDetails.indicator4;
        this.indicator5 = memberDetails.indicator5;
        this.indicator6 = memberDetails.indicator6;
        this.indicator7 = memberDetails.indicator7;
        this.indicator8 = memberDetails.indicator8;
        this.indicator9 = memberDetails.indicator9;
        this.indicator10 = memberDetails.indicator10;
        this.indicator11 = memberDetails.indicator11;
        this.indicator12 = memberDetails.indicator12;
        this.indicator13 = memberDetails.indicator13;
        this.indicator14 = memberDetails.indicator14;
        this.indicator15 = memberDetails.indicator15;
        this.indicator16 = memberDetails.indicator16;
        this.indicator17 = memberDetails.indicator17;
        this.indicator18 = memberDetails.indicator18;
        this.indicator19 = memberDetails.indicator19;
        this.indicator20 = memberDetails.indicator20;
        this.indicator21 = memberDetails.indicator21;
        this.indicator22 = memberDetails.indicator22;
        this.indicator23 = memberDetails.indicator23;
        this.indicator24 = memberDetails.indicator24;
        this.indicator25 = memberDetails.indicator25;
        this.indicator26 = memberDetails.indicator26;
        this.indicator27 = memberDetails.indicator27;
        this.indicator28 = memberDetails.indicator28;
        this.indicator29 = memberDetails.indicator29;
        this.indicator30 = memberDetails.indicator30;
        this.indicator31 = memberDetails.indicator31;
        this.indicator32 = memberDetails.indicator32;
        this.indicator33 = memberDetails.indicator33;
        this.indicator34 = memberDetails.indicator34;
        this.indicator35 = memberDetails.indicator35;
        this.indicator36 = memberDetails.indicator36;
        this.indicator37 = memberDetails.indicator37;
        this.indicator38 = memberDetails.indicator38;
        this.indicator39 = memberDetails.indicator39;
        this.indicator40 = memberDetails.indicator40;
        this.dateField1 = memberDetails.dateField1;
        this.dateField2 = memberDetails.dateField2;
        this.alpha10Field1 = memberDetails.alpha10Field1;
        this.alpha10Field2 = memberDetails.alpha10Field2;
        this.alpha20Field1 = memberDetails.alpha20Field1;
        this.alpha20Field2 = memberDetails.alpha20Field2;
        this.numericField1 = memberDetails.numericField1;
        this.numericField2 = memberDetails.numericField2;
        this.iAkaunLoginUserId = memberDetails.iAkaunLoginUserId;
        this.iAkaunStatus = memberDetails.iAkaunStatus;
        this.pinReqDate = memberDetails.pinReqDate;
        this.firstLoginDate = memberDetails.firstLoginDate;
        this.lastLoginDate = memberDetails.lastLoginDate;
        this.lastIAkaunStatusChgDate = memberDetails.lastIAkaunStatusChgDate;
        this.cfiwiaCreationDate = memberDetails.cfiwiaCreationDate;
        this.cfiwiaLastMaintDate = memberDetails.cfiwiaLastMaintDate;
        this.closeStatusReasonCodeDesc = memberDetails.closeStatusReasonCodeDesc;
        this.replaceMinutiae = memberDetails.replaceMinutiae;
        this.tacMobilePhone = memberDetails.tacMobilePhone;
        this.tacMobilePhoneStatus = memberDetails.tacMobilePhoneStatus;
        this.activeContribTransferIndicator = memberDetails.activeContribTransferIndicator;
    }
}

export class currentMemberAddress {
    addSeq: string;
    addLine1: string;
    addLine2: string;
    addLine3: string;
    addLine4: string;
    addLine5: string;
    cityStateZip: string;
    postalCode: string;
    stateCode: string;
    countryCode: string;
    remarks: string;

    constructor(memberAddress: any){
        this.addSeq = memberAddress.addSeq;
        this.addLine1 = memberAddress.addLine1;
        this.addLine2 = memberAddress.addLine2;
        this.addLine3 = memberAddress.addLine3;
        this.addLine4 = memberAddress.addLine4;
        this.addLine5 = memberAddress.addLine5;
        this.cityStateZip = memberAddress.cityStateZip;
        this.postalCode = memberAddress.postalCode;
        this.stateCode = memberAddress.stateCode;
        this.countryCode = memberAddress.countryCode;
        this.remarks = memberAddress.remarks;
    }
}

export class currMemberAddress {
    addSeq: string;
    addLine1: string;
    addLine2: string;
    addLine3: string;
    addLine4: string;
    addLine5: string;
    cityStateZip: string;
    postalCode: string;
    stateCode: string;
    stateDesc: string;
    countryCode: string;
    countryDesc: string;
    remarks: string;

    constructor(mbrAddress: any) {
        this.addSeq = mbrAddress.addSeq;
        this.addLine1 = mbrAddress.addLine1;
        this.addLine2 = mbrAddress.addLine2;
        this.addLine3 = mbrAddress.addLine3;
        this.addLine4 = mbrAddress.addLine4;
        this.addLine5 = mbrAddress.addLine5;
        this.cityStateZip = mbrAddress.cityStateZip;
        this.postalCode = mbrAddress.postalCode;
        this.stateCode = mbrAddress.stateCode;
        this.stateDesc = mbrAddress.stateDesc;
        this.countryCode = mbrAddress.countryCode;
        this.countryDesc = mbrAddress.countryDesc;
        this.remarks = mbrAddress.remarks;
    }
}

export class currMemberDetails {
    cifNum: string;
    custName: string;
    birthDate: string;
    gender: string;
    citizenCountry: string;
    race: string;
    religion: string;
    regChannel: string;
    regLocation: string;
    regRcvdDate: string;
    epfRegDate: string;
    matrimAsset: string;
    handicapRemarks: string;
    residentStatus: string;
    homePhone: string;
    officePhone: string;
    mobilePhone: string;
    faxNum: string;
    emailAdd: string;
    electAddGrpSeq: string;
    prefComChannel: string;
    webPage: string;
    addresses: currMemberAddress[];
    businessType: string;
    blacklistIndicator: string;
    accStatus: string;
    accStatusDesc: string;
    primaryIdType: string;
    primaryIdTypeDesc: string;
    primaryIdNum: string;
    cifCategory: string;
    lastNominationDate: string;
    relatedLinkCode: string;
    deceasedDate: string;
    ageYears: string;
    ageMonths: string;
    maritalStatus: string;
    nomineeCheck: string;
    thumbVerifiedDate: string;
    accNum: string;
    freezeAccStatus: string;
    indicator1: string;
    indicator2: string;
    indicator3: string;
    indicator4: string;
    indicator5: string;
    indicator6: string;
    indicator7: string;
    indicator8: string;
    indicator9: string;
    indicator10: string;
    indicator11: string;
    indicator12: string;
    indicator13: string;
    indicator14: string;
    indicator15: string;
    indicator16: string;
    indicator17: string;
    indicator18: string;
    indicator19: string;
    indicator20: string;
    indicator31: string;
    indicator32: string;
    indicator33: string;
    indicator34: string;
    indicator35: string;
    indicator36: string;
    indicator37: string;
    indicator38: string;
    indicator39: string;
    indicator40: string;
    iAkaunLoginUserId: string;
    iAkaunStatus: string;
    pinReqDate: string;
    firstLoginDate: string;
    lastLoginDate: string;
    lastIAkaunStatusChgDate: string;
    cfiwiaCreationDate: string;
    cfiwiaLastMaintDate: string;
    closeStatusReasonCodeDesc: string;
    replaceMinutiae: string;
    tacMobilePhone: string;
    tacMobilePhoneStatus: string;
    activeContribTransferIndicator: string;
    wifeContribTransferIndicator: string;
    effectiveDate: string;
    islamicFlag: string;

    constructor(mbrDetails: any){
        this.cifNum = mbrDetails.cifNum;
        this.custName = mbrDetails.custName;
        this.birthDate = mbrDetails.birthDate;
        this.gender = mbrDetails.gender;
        this.citizenCountry = mbrDetails.citizenCountry;
        this.race = mbrDetails.race;
        this.religion = mbrDetails.religion;
        this.regChannel = mbrDetails.regChannel;
        this.regLocation = mbrDetails.regLocation;
        this.regRcvdDate = mbrDetails.regRcvdDate;
        this.epfRegDate = mbrDetails.epfRegDate;
        this.matrimAsset = mbrDetails.matrimAsset;
        this.handicapRemarks = mbrDetails.handicapRemarks;
        this.residentStatus = mbrDetails.residentStatus;
        this.homePhone = mbrDetails.homePhone;
        this.officePhone = mbrDetails.officePhone;
        this.mobilePhone = mbrDetails.mobilePhone;
        this.faxNum = mbrDetails.valfaxNumue;
        this.emailAdd = mbrDetails.emailAdd;
        this.electAddGrpSeq = mbrDetails.electAddGrpSeq;
        this.prefComChannel = mbrDetails.prefComChannel;
        this.webPage = mbrDetails.webPage;
        this.addresses = mbrDetails.addresses.map((add: any) => new currMemberAddress(add)),
        this.businessType = mbrDetails.businessType;
        this.blacklistIndicator = mbrDetails.blacklistIndicator;
        this.accStatus = mbrDetails.accStatus;
        this.accStatusDesc = mbrDetails.accStatusDesc;
        this.primaryIdType = mbrDetails.primaryIdType;
        this.primaryIdTypeDesc = mbrDetails.primaryIdTypeDesc;
        this.primaryIdNum = mbrDetails.primaryIdNum;
        this.cifCategory = mbrDetails.cifCategory;
        this.lastNominationDate = mbrDetails.lastNominationDate;
        this.relatedLinkCode = mbrDetails.relatedLinkCode;
        this.deceasedDate = mbrDetails.deceasedDate;
        this.ageYears = mbrDetails.ageYears;
        this.ageMonths = mbrDetails.ageMonths;
        this.maritalStatus = mbrDetails.maritalStatus;
        this.nomineeCheck = mbrDetails.nomineeCheck;
        this.thumbVerifiedDate = mbrDetails.thumbVerifiedDate;
        this.accNum = mbrDetails.accNum;
        this.freezeAccStatus = mbrDetails.freezeAccStatus;
        this.indicator1 = mbrDetails.indicator1;
        this.indicator2 = mbrDetails.indicator2;
        this.indicator3 = mbrDetails.indicator3;
        this.indicator4 = mbrDetails.indicator4;
        this.indicator5 = mbrDetails.indicator5;
        this.indicator6 = mbrDetails.indicator6;
        this.indicator7 = mbrDetails.indicator7;
        this.indicator8 = mbrDetails.indicator8;
        this.indicator9 = mbrDetails.indicator9;
        this.indicator10 = mbrDetails.indicator10;
        this.indicator11 = mbrDetails.indicator11;
        this.indicator12 = mbrDetails.indicator12;
        this.indicator13 = mbrDetails.indicator13;
        this.indicator14 = mbrDetails.indicator14;
        this.indicator15 = mbrDetails.indicator15;
        this.indicator16 = mbrDetails.indicator16;
        this.indicator17 = mbrDetails.indicator17;
        this.indicator18 = mbrDetails.indicator18;
        this.indicator19 = mbrDetails.indicator19;
        this.indicator20 = mbrDetails.indicator20;
        this.indicator31 = mbrDetails.indicator31;
        this.indicator32 = mbrDetails.indicator32;
        this.indicator33 = mbrDetails.indicator33;
        this.indicator34 = mbrDetails.indicator34;
        this.indicator35 = mbrDetails.indicator35;
        this.indicator36 = mbrDetails.indicator36;
        this.indicator37 = mbrDetails.indicator37;
        this.indicator38 = mbrDetails.indicator38;
        this.indicator39 = mbrDetails.indicator39;
        this.indicator40 = mbrDetails.indicator40;
        this.iAkaunLoginUserId = mbrDetails.iAkaunLoginUserId;
        this.iAkaunStatus = mbrDetails.iAkaunStatus;
        this.pinReqDate = mbrDetails.pinReqDate;
        this.firstLoginDate = mbrDetails.firstLoginDate;
        this.lastLoginDate = mbrDetails.lastLoginDate;
        this.lastIAkaunStatusChgDate = mbrDetails.lastIAkaunStatusChgDate;
        this.cfiwiaCreationDate = mbrDetails.cfiwiaCreationDate;
        this.cfiwiaLastMaintDate = mbrDetails.cfiwiaLastMaintDate;
        this.closeStatusReasonCodeDesc = mbrDetails.closeStatusReasonCodeDesc;
        this.replaceMinutiae = mbrDetails.replaceMinutiae;
        this.tacMobilePhone = mbrDetails.tacMobilePhone;
        this.tacMobilePhoneStatus = mbrDetails.tacMobilePhoneStatus;
        this.activeContribTransferIndicator = mbrDetails.activeContribTransferIndicator;
        this.wifeContribTransferIndicator = mbrDetails.wifeContribTransferIndicator;
        this.effectiveDate = mbrDetails.effectiveDate;
        this.islamicFlag = mbrDetails.islamicFlag;
    }
}